# Generated by Django 4.2.15 on 2024-09-03 21:32

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('subcategory', models.CharField(max_length=50, verbose_name='Subcategoria')),
                ('desciption', models.CharField(max_length=500, verbose_name='Descipcion')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ['pk', 'category', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INC', 'Incidente'), ('VUL', 'Vulnerabilidad'), ('EVE', 'Evento')], default='INC', max_length=50, verbose_name='Tipo')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('lastUpdate', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.DurationField(blank=True, null=True, verbose_name='Resolucion')),
                ('severity', models.CharField(default='NULA', max_length=7, verbose_name='Severidad')),
                ('impact', models.CharField(default='NULO', max_length=10, verbose_name='Impacto')),
                ('status', models.CharField(default='ABIERTO', max_length=9, verbose_name='Estado')),
                ('resume', models.CharField(max_length=300, verbose_name='Resumen')),
                ('captures', models.ImageField(upload_to=core.models.ticket_capture_upload_to, verbose_name='Capturas')),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='core.ticketcategory', verbose_name='Categoria')),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'ordering': None,
            },
        ),
    ]
