# Generated by Django 4.2.15 on 2024-09-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreport',
            name='ticketRel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.ticket', verbose_name='Ticket'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('CRITICO', 'Critica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja'), ('NULA', 'Nula')], default='NULA', max_length=7, verbose_name='Severidad'),
        ),
    ]
