# Generated by Django 4.2.15 on 2024-09-06 16:13

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', django_quill.fields.QuillField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['name', 'subcategory'], 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RenameField(
            model_name='ticketcategory',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='captures',
        ),
        migrations.RemoveField(
            model_name='ticketcategory',
            name='desciption',
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='description',
            field=models.CharField(default=None, max_length=500, unique=True, verbose_name='Descipcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='subcategory',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subcategoria'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='core.ticketreport', verbose_name='Report'),
        ),
    ]
