# Generated by Django 4.2.15 on 2024-09-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticketreport_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.CharField(choices=[('CRITICO', 'Critica'), ('IMPORTANTE', 'Importante'), ('MODERADO', 'Moderado'), ('BAJO', 'Bajo'), ('NULO', 'Nulo')], default='NULO', max_length=10, verbose_name='Impacto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.CharField(choices=[('CRITICA', 'Critica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja'), ('NULA', 'Nula')], default='NULA', max_length=7, verbose_name='Severidad'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('TRAMITADO', 'Tramitado'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descripcion'),
        ),
    ]
