# Generated by Django 4.2.15 on 2024-09-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticketreport_ticketrel_alter_ticket_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreport',
            name='ticketRel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='core.ticket', verbose_name='Ticket'),
        ),
    ]
