# Generated by Django 4.2.15 on 2024-09-12 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticket_impact_alter_ticket_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='core.ticketreport', verbose_name='Reporte'),
        ),
    ]
