# Generated by Django 4.2.15 on 2024-09-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ticketreport_ticketrel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticketreport',
            old_name='ticketRel',
            new_name='ticket',
        ),
    ]
