# Generated by Django 4.2.15 on 2024-09-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ticketrel_ticketreport_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketreport',
            name='ticket',
        ),
        migrations.AddField(
            model_name='ticketreport',
            name='title',
            field=models.CharField(default='Informe <django.db.models.fields.DateTimeField>', max_length=50, verbose_name='Titulo'),
        ),
    ]
