# Generated by Django 4.2.15 on 2024-09-15 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-pk'], 'verbose_name_plural': 'Tickets'},
        ),
    ]
